In [518]:
def sum_bound(array,co_list):
        ex=array[0,0]+array[0,co_list[1]-1]+array[co_list[0]-1,0]+array[co_list[0]-1,co_list[1]-1]
        return sum(array[co_list[0]-1,:])+sum(array[0,:])+sum(array[:,0])+sum(array[:,co_list[1]-1])-ex
    
def partial(array,row_start,col_start,row_end,col_end):
    matrica=array[row_start:row_end+1,col_start:col_end+1]
    lista=[row_end+1-row_start,col_end+1-col_start]
    return sum_bound(matrica,lista)


def max_sum_matr(array):
    lista_sum=[]
    lista_dimen=[]  
    for l in range(0,5):
        for j in range(1,5):
            k=0
            while k<5:
                for i in range(1,5):
                    if j-l>1 and i+1-k>1 and len((array[l:j,k:i]))>1:
                        sub_matrica=array[l:j,k:i]
                        co_list=[j-l,i-k]
                        lista_dimen.append((l,k,j,i))
                        lista_sum.append(sum_bound(sub_matrica,co_list))
                k=k+1
    print ((max(lista_sum)))
    axes=lista_dimen[lista_sum.index(max(lista_sum))]
    print (axes)
    print (matrix[axes[0]:axes[2],axes[1]:axes[3]])
    
    

def bound():
    import numpy as np
    coordinate=list(map(int,input("provide matrix dimensions").split(" ")))
    elements=list(map(int,input("").split(" ")))
    matr=np.array(elements).reshape(coordinate[0],coordinate[1])
    #print (sum_bound(matr,coordinate))
    max_sum_matr(matr)


In [519]:
bound()

provide matrix dimensions4 5
1 8 1 1 1 1 1 1 9 1 1 1 9 1 1 0 1 1 1 0
33
(0, 0, 3, 4)
[[1 8 1 1]
 [1 1 1 9]
 [1 1 9 1]]
